Add missing -lz to linker stage for brdf
on ubuntu 14.04 the omission of -lz causes the following error:

Linking CXX executable brdf
/usr/bin/ld: CMakeFiles/brdf.dir/src/brdf/ptex/PtexReader.cpp.o: undefined reference to symbol 'inflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line